// Demo/mock data for development when database is not connected

export const demoUsers = [
  {
    id: "usr_001",
    email: "admin@nuanu.com",
    name: "Sarah Chen",
    avatar: null,
    roles: ["super_admin"],
    departmentId: "dept_001",
    phone: "+1234567890",
    isActive: true,
  },
  {
    id: "usr_002",
    email: "hr@nuanu.com",
    name: "James Wilson",
    avatar: null,
    roles: ["hr_admin"],
    departmentId: "dept_002",
    phone: "+1234567891",
    isActive: true,
  },
  {
    id: "usr_003",
    email: "recruiter@nuanu.com",
    name: "Maria Santos",
    avatar: null,
    roles: ["recruiter"],
    departmentId: "dept_002",
    phone: "+1234567892",
    isActive: true,
  },
];

export const demoDepartments = [
  { id: "dept_001", name: "Executive", code: "EXEC", headId: "usr_001", budget: 500000 },
  { id: "dept_002", name: "Human Resources", code: "HR", headId: "usr_002", budget: 350000 },
  { id: "dept_003", name: "Engineering", code: "ENG", headId: null, budget: 1200000 },
  { id: "dept_004", name: "Product", code: "PROD", headId: null, budget: 800000 },
  { id: "dept_005", name: "Marketing", code: "MKT", headId: null, budget: 450000 },
  { id: "dept_006", name: "Finance", code: "FIN", headId: null, budget: 300000 },
  { id: "dept_007", name: "Operations", code: "OPS", headId: null, budget: 600000 },
  { id: "dept_008", name: "Design", code: "DES", headId: null, budget: 400000 },
];

export const demoVacancies = [
  {
    id: "vac_001",
    title: "Senior Full Stack Developer",
    code: "ENG-2024-001",
    departmentId: "dept_003",
    department: { name: "Engineering" },
    creatorId: "usr_002",
    recruiterId: "usr_003",
    status: "published",
    priority: "high",
    headcount: 3,
    filledCount: 1,
    employmentType: "full-time",
    locationType: "hybrid",
    location: "Bali, Indonesia",
    salaryMin: 80000,
    salaryMax: 120000,
    currency: "USD",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL", "AWS"],
    experienceMin: 5,
    experienceMax: 8,
    applicationCount: 47,
    publishedAt: "2024-03-01",
    targetHireDate: "2024-04-30",
    createdAt: "2024-02-15",
  },
  {
    id: "vac_002",
    title: "UX/UI Designer",
    code: "DES-2024-002",
    departmentId: "dept_008",
    department: { name: "Design" },
    creatorId: "usr_002",
    recruiterId: "usr_003",
    status: "published",
    priority: "medium",
    headcount: 2,
    filledCount: 0,
    employmentType: "full-time",
    locationType: "onsite",
    location: "Bali, Indonesia",
    salaryMin: 60000,
    salaryMax: 90000,
    currency: "USD",
    skills: ["Figma", "Design Systems", "Prototyping", "User Research"],
    experienceMin: 3,
    experienceMax: 6,
    applicationCount: 32,
    publishedAt: "2024-03-05",
    targetHireDate: "2024-05-15",
    createdAt: "2024-02-20",
  },
  {
    id: "vac_003",
    title: "Product Manager",
    code: "PROD-2024-003",
    departmentId: "dept_004",
    department: { name: "Product" },
    creatorId: "usr_001",
    recruiterId: "usr_003",
    status: "pending_approval",
    priority: "high",
    headcount: 1,
    filledCount: 0,
    employmentType: "full-time",
    locationType: "remote",
    location: "Remote",
    salaryMin: 90000,
    salaryMax: 130000,
    currency: "USD",
    skills: ["Product Strategy", "Agile", "Data Analysis", "Stakeholder Management"],
    experienceMin: 5,
    experienceMax: 10,
    applicationCount: 18,
    publishedAt: null,
    targetHireDate: "2024-06-01",
    createdAt: "2024-03-01",
  },
  {
    id: "vac_004",
    title: "Marketing Manager",
    code: "MKT-2024-004",
    departmentId: "dept_005",
    department: { name: "Marketing" },
    creatorId: "usr_002",
    recruiterId: "usr_003",
    status: "published",
    priority: "medium",
    headcount: 1,
    filledCount: 0,
    employmentType: "full-time",
    locationType: "hybrid",
    location: "Bali, Indonesia",
    salaryMin: 70000,
    salaryMax: 100000,
    currency: "USD",
    skills: ["Digital Marketing", "SEO", "Content Strategy", "Analytics"],
    experienceMin: 4,
    experienceMax: 7,
    applicationCount: 25,
    publishedAt: "2024-03-10",
    targetHireDate: "2024-05-30",
    createdAt: "2024-03-05",
  },
  {
    id: "vac_005",
    title: "Financial Analyst",
    code: "FIN-2024-005",
    departmentId: "dept_006",
    department: { name: "Finance" },
    creatorId: "usr_001",
    recruiterId: "usr_002",
    status: "draft",
    priority: "low",
    headcount: 1,
    filledCount: 0,
    employmentType: "full-time",
    locationType: "onsite",
    location: "Bali, Indonesia",
    salaryMin: 55000,
    salaryMax: 80000,
    currency: "USD",
    skills: ["Financial Modeling", "Excel", "SAP", "Reporting"],
    experienceMin: 2,
    experienceMax: 5,
    applicationCount: 0,
    publishedAt: null,
    targetHireDate: "2024-07-01",
    createdAt: "2024-03-15",
  },
  {
    id: "vac_006",
    title: "DevOps Engineer",
    code: "ENG-2024-006",
    departmentId: "dept_003",
    department: { name: "Engineering" },
    creatorId: "usr_002",
    recruiterId: "usr_003",
    status: "published",
    priority: "high",
    headcount: 2,
    filledCount: 0,
    employmentType: "full-time",
    locationType: "remote",
    location: "Remote",
    salaryMin: 85000,
    salaryMax: 130000,
    currency: "USD",
    skills: ["Docker", "Kubernetes", "AWS", "Terraform", "CI/CD"],
    experienceMin: 4,
    experienceMax: 8,
    applicationCount: 21,
    publishedAt: "2024-03-12",
    targetHireDate: "2024-05-20",
    createdAt: "2024-03-10",
  },
];

export const demoCandidates = [
  {
    id: "cand_001",
    name: "Alex Johnson",
    email: "alex.johnson@email.com",
    avatar: null,
    currentTitle: "Full Stack Developer",
    currentCompany: "TechCorp",
    skills: ["React", "Node.js", "TypeScript", "PostgreSQL"],
    experienceYears: 6,
    location: "San Francisco, CA",
    score: 92,
    stage: "final_interview",
    vacancyId: "vac_001",
    vacancyTitle: "Senior Full Stack Developer",
    appliedAt: "2024-03-05",
    source: "linkedin",
    tags: ["top_candidate", "referral"],
  },
  {
    id: "cand_002",
    name: "Emma Davis",
    email: "emma.davis@email.com",
    avatar: null,
    currentTitle: "Senior Developer",
    currentCompany: "InnovateTech",
    skills: ["React", "TypeScript", "AWS", "Python"],
    experienceYears: 7,
    location: "London, UK",
    score: 88,
    stage: "hr_interview",
    vacancyId: "vac_001",
    vacancyTitle: "Senior Full Stack Developer",
    appliedAt: "2024-03-07",
    source: "indeed",
    tags: ["experienced"],
  },
  {
    id: "cand_003",
    name: "Ryan Park",
    email: "ryan.park@email.com",
    avatar: null,
    currentTitle: "UI/UX Designer",
    currentCompany: "DesignStudio",
    skills: ["Figma", "Design Systems", "Prototyping", "CSS"],
    experienceYears: 4,
    location: "Seoul, Korea",
    score: 85,
    stage: "screening",
    vacancyId: "vac_002",
    vacancyTitle: "UX/UI Designer",
    appliedAt: "2024-03-10",
    source: "direct",
    tags: ["portfolio_strong"],
  },
  {
    id: "cand_004",
    name: "Lisa Zhang",
    email: "lisa.zhang@email.com",
    avatar: null,
    currentTitle: "Product Lead",
    currentCompany: "ScaleUp Inc",
    skills: ["Product Strategy", "Agile", "Data Analysis", "Leadership"],
    experienceYears: 8,
    location: "Singapore",
    score: 94,
    stage: "user_interview",
    vacancyId: "vac_003",
    vacancyTitle: "Product Manager",
    appliedAt: "2024-03-12",
    source: "referral",
    tags: ["top_candidate", "senior"],
  },
  {
    id: "cand_005",
    name: "Michael Brown",
    email: "michael.brown@email.com",
    avatar: null,
    currentTitle: "Marketing Specialist",
    currentCompany: "MediaHouse",
    skills: ["Digital Marketing", "SEO", "Google Ads", "Content"],
    experienceYears: 5,
    location: "Sydney, Australia",
    score: 79,
    stage: "applied",
    vacancyId: "vac_004",
    vacancyTitle: "Marketing Manager",
    appliedAt: "2024-03-15",
    source: "jobstreet",
    tags: [],
  },
  {
    id: "cand_006",
    name: "Sofia Martinez",
    email: "sofia.martinez@email.com",
    avatar: null,
    currentTitle: "Frontend Developer",
    currentCompany: "WebAgency",
    skills: ["React", "Vue.js", "TypeScript", "Tailwind CSS"],
    experienceYears: 4,
    location: "Barcelona, Spain",
    score: 76,
    stage: "screening",
    vacancyId: "vac_001",
    vacancyTitle: "Senior Full Stack Developer",
    appliedAt: "2024-03-08",
    source: "linkedin",
    tags: ["frontend_focus"],
  },
  {
    id: "cand_007",
    name: "David Kim",
    email: "david.kim@email.com",
    avatar: null,
    currentTitle: "DevOps Engineer",
    currentCompany: "CloudFirst",
    skills: ["Docker", "Kubernetes", "AWS", "Terraform", "Jenkins"],
    experienceYears: 6,
    location: "Tokyo, Japan",
    score: 91,
    stage: "offer",
    vacancyId: "vac_006",
    vacancyTitle: "DevOps Engineer",
    appliedAt: "2024-03-14",
    source: "linkedin",
    tags: ["top_candidate"],
  },
  {
    id: "cand_008",
    name: "Priya Patel",
    email: "priya.patel@email.com",
    avatar: null,
    currentTitle: "Senior Designer",
    currentCompany: "CreativeLab",
    skills: ["Figma", "Adobe XD", "User Research", "Design Systems"],
    experienceYears: 5,
    location: "Mumbai, India",
    score: 83,
    stage: "hr_interview",
    vacancyId: "vac_002",
    vacancyTitle: "UX/UI Designer",
    appliedAt: "2024-03-11",
    source: "indeed",
    tags: ["experienced"],
  },
];

export const demoPipelineCandidates = {
  applied: [
    { id: "cand_005", applicationId: "app_005", name: "Michael Brown", position: "Marketing Manager", score: 79, appliedAt: "2024-03-15", stage: "applied", tags: [] },
    { id: "cand_009", applicationId: "app_009", name: "Anna Lee", position: "Senior Full Stack Developer", score: 72, appliedAt: "2024-03-16", stage: "applied", tags: ["new"] },
  ],
  screening: [
    { id: "cand_003", applicationId: "app_003", name: "Ryan Park", position: "UX/UI Designer", score: 85, appliedAt: "2024-03-10", stage: "screening", tags: ["portfolio_strong"] },
    { id: "cand_006", applicationId: "app_006", name: "Sofia Martinez", position: "Senior Full Stack Developer", score: 76, appliedAt: "2024-03-08", stage: "screening", tags: ["frontend_focus"] },
  ],
  hr_interview: [
    { id: "cand_002", applicationId: "app_002", name: "Emma Davis", position: "Senior Full Stack Developer", score: 88, appliedAt: "2024-03-07", stage: "hr_interview", tags: ["experienced"] },
    { id: "cand_008", applicationId: "app_008", name: "Priya Patel", position: "UX/UI Designer", score: 83, appliedAt: "2024-03-11", stage: "hr_interview", tags: ["experienced"] },
  ],
  user_interview: [
    { id: "cand_004", applicationId: "app_004", name: "Lisa Zhang", position: "Product Manager", score: 94, appliedAt: "2024-03-12", stage: "user_interview", tags: ["top_candidate", "senior"] },
  ],
  final_interview: [
    { id: "cand_001", applicationId: "app_001", name: "Alex Johnson", position: "Senior Full Stack Developer", score: 92, appliedAt: "2024-03-05", stage: "final_interview", tags: ["top_candidate", "referral"] },
  ],
  offer: [
    { id: "cand_007", applicationId: "app_007", name: "David Kim", position: "DevOps Engineer", score: 91, appliedAt: "2024-03-14", stage: "offer", tags: ["top_candidate"] },
  ],
  hired: [],
};

export const demoNotifications = [
  { id: "notif_001", type: "approval", title: "Approval Required", message: "Product Manager vacancy requires your approval", link: "/dashboard/jobs/vac_003", isRead: false, createdAt: "2024-03-20T10:30:00Z" },
  { id: "notif_002", type: "interview", title: "Interview Scheduled", message: "Interview with Alex Johnson scheduled for tomorrow at 2:00 PM", link: "/dashboard/interviews", isRead: false, createdAt: "2024-03-20T09:15:00Z" },
  { id: "notif_003", type: "offer", title: "Offer Accepted", message: "David Kim has accepted the offer for DevOps Engineer position", link: "/dashboard/offers", isRead: false, createdAt: "2024-03-19T16:45:00Z" },
  { id: "notif_004", type: "system", title: "New Application", message: "12 new applications received today across all positions", link: "/dashboard/candidates", isRead: true, createdAt: "2024-03-19T14:00:00Z" },
  { id: "notif_005", type: "reminder", title: "Feedback Pending", message: "Please submit interview feedback for Emma Davis", link: "/dashboard/interviews", isRead: true, createdAt: "2024-03-18T11:30:00Z" },
];

export const demoInterviews = [
  {
    id: "int_001",
    applicationId: "app_001",
    candidateName: "Alex Johnson",
    candidateAvatar: null,
    position: "Senior Full Stack Developer",
    type: "onsite",
    stage: "final_interview",
    scheduledAt: "2024-03-25T14:00:00Z",
    duration: 60,
    location: "Nuanu HQ, Meeting Room A",
    interviewerName: "Sarah Chen",
    status: "scheduled",
  },
  {
    id: "int_002",
    applicationId: "app_002",
    candidateName: "Emma Davis",
    candidateAvatar: null,
    position: "Senior Full Stack Developer",
    type: "video",
    stage: "hr_interview",
    scheduledAt: "2024-03-22T10:00:00Z",
    duration: 45,
    location: "Google Meet",
    meetingUrl: "https://meet.google.com/abc-defg-hij",
    interviewerName: "James Wilson",
    status: "confirmed",
  },
  {
    id: "int_003",
    applicationId: "app_004",
    candidateName: "Lisa Zhang",
    candidateAvatar: null,
    position: "Product Manager",
    type: "video",
    stage: "user_interview",
    scheduledAt: "2024-03-23T15:30:00Z",
    duration: 60,
    location: "Zoom",
    meetingUrl: "https://zoom.us/j/123456789",
    interviewerName: "Maria Santos",
    status: "scheduled",
  },
  {
    id: "int_004",
    applicationId: "app_008",
    candidateName: "Priya Patel",
    candidateAvatar: null,
    position: "UX/UI Designer",
    type: "video",
    stage: "hr_interview",
    scheduledAt: "2024-03-24T11:00:00Z",
    duration: 45,
    location: "Google Meet",
    interviewerName: "James Wilson",
    status: "scheduled",
  },
];

export const demoOffers = [
  {
    id: "offer_001",
    applicationId: "app_007",
    candidateName: "David Kim",
    position: "DevOps Engineer",
    salary: 110000,
    currency: "USD",
    salaryPeriod: "annual",
    bonus: 10000,
    startDate: "2024-05-01",
    status: "accepted",
    sentAt: "2024-03-18",
    respondedAt: "2024-03-19",
  },
];

export const demoAnalytics = {
  totalVacancies: 12,
  activeVacancies: 8,
  totalCandidates: 156,
  newCandidatesThisMonth: 47,
  interviewsScheduled: 18,
  offersExtended: 5,
  offersAccepted: 3,
  averageTimeToHire: 32,
  averageCostPerHire: 4250,
  offerAcceptanceRate: 78,
  averageMatchScore: 82,
  hiringByDepartment: [
    { department: "Engineering", open: 5, filled: 2, candidates: 68 },
    { department: "Design", open: 2, filled: 0, candidates: 32 },
    { department: "Product", open: 1, filled: 0, candidates: 18 },
    { department: "Marketing", open: 1, filled: 0, candidates: 25 },
    { department: "Finance", open: 1, filled: 0, candidates: 8 },
    { department: "Operations", open: 2, filled: 1, candidates: 15 },
  ],
  pipelineFunnel: [
    { stage: "Applied", count: 156 },
    { stage: "Screening", count: 89 },
    { stage: "HR Interview", count: 52 },
    { stage: "User Interview", count: 28 },
    { stage: "Final Interview", count: 15 },
    { stage: "Offer", count: 8 },
    { stage: "Hired", count: 5 },
  ],
  monthlyApplications: [
    { month: "Oct", applications: 45, hires: 3 },
    { month: "Nov", applications: 52, hires: 4 },
    { month: "Dec", applications: 38, hires: 2 },
    { month: "Jan", applications: 67, hires: 5 },
    { month: "Feb", applications: 73, hires: 4 },
    { month: "Mar", applications: 89, hires: 6 },
  ],
  candidateSourceBreakdown: [
    { source: "LinkedIn", count: 62, percentage: 40 },
    { source: "Indeed", count: 35, percentage: 22 },
    { source: "Direct", count: 28, percentage: 18 },
    { source: "Referral", count: 19, percentage: 12 },
    { source: "JobStreet", count: 12, percentage: 8 },
  ],
  matchScoreDistribution: [
    { range: "90-100", count: 12 },
    { range: "80-89", count: 28 },
    { range: "70-79", count: 45 },
    { range: "60-69", count: 38 },
    { range: "50-59", count: 22 },
    { range: "Below 50", count: 11 },
  ],
  recentActivity: [
    { id: "act_001", action: "New application received", resource: "Alex Johnson → Senior Full Stack Developer", time: "2 hours ago", type: "application" },
    { id: "act_002", action: "Interview completed", resource: "Emma Davis → HR Interview", time: "3 hours ago", type: "interview" },
    { id: "act_003", action: "Offer accepted", resource: "David Kim → DevOps Engineer", time: "5 hours ago", type: "offer" },
    { id: "act_004", action: "Vacancy approved", resource: "Marketing Manager", time: "6 hours ago", type: "approval" },
    { id: "act_005", action: "AI score updated", resource: "Lisa Zhang — 94% match", time: "8 hours ago", type: "score" },
    { id: "act_006", action: "New vacancy created", resource: "Financial Analyst", time: "1 day ago", type: "vacancy" },
    { id: "act_007", action: "Candidate moved to Final Interview", resource: "Alex Johnson", time: "1 day ago", type: "pipeline" },
    { id: "act_008", action: "Feedback submitted", resource: "Ryan Park — User Interview", time: "2 days ago", type: "feedback" },
  ],
};
